### ISSUE TITLE
Inexor Lifecycle (Initialising Inexor Tree, RPC and parsing command line options)

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-core#354]
## Lifecycle

Inexor Flex (NodeJS) starts a new instance of Inexor Core (C++). Command line options parsing and reading configuration files is done in Inexor Flex only. Inexor Core have to use the Inexor Tree instead. This prepares Inexor for multi-instance capabilities.

### Startup of Inexor Flex

1. The user starts Inexor Flex
2. Inexor Flex checks if there is a running instance of Inexor Flex already
3. Inexor Flex initializes the [Inexor Tree](/inexor-game/code/wiki/Inexor-Tree) with default values from the proto file
4. Inexor Flex automatically detects media paths (currently done by batch files) and stores the paths into the Inexor Tree
5. Inexor Flex loads TOML configuration file describing the list of instances and populates the Inexor Tree
    * This may start instances of Inexor Core (autostart = true)

### Startup of Inexor Core

1. Inexor Flex starts an instance of Inexor Core (see #362)
    * Pass the port / instance id as command line argument to Inexor Core
2. First, Inexor Core initializes the RPC subsystem
    * Using the port / instance id
3. Inexor Flex waits until the port available
4. When the port is available, Inexor Flex connects to the RPC subsystem of Inexor Core
5. Now the Inexor Tree will be synchronized
6. After this Inexor Core is fully configured and can use the Inexor Tree for further initialization like opening the SDL window

### Shutdown of Inexor Core

1. Inexor Core synchronizes the Inexor Tree for the last time
2. Inexor Core terminates the RPC connection(s)
3. Inexor Core exits
4. When the RPC connection has been terminated Inexor Flex saves the relevant information of the Inexor Tree into a TOML file and removes the Inexor Tree of the terminated instance of Inexor Core

### Tasks

- [x] The Command Line API is able to start an instance
- [x] The Command Line API handles `inexor:` URLs
- [x] Only one instance of Inexor Flex is allowed
- [x] If flex is not running and a command shall be executed via the Command Line API, start Inexor Flex first
- [x] Create a default `instances.toml`
- [x] Remove the deprecated Node stuff from `core`
- [x] At starting Inexor Flex, load the list of instances from `instances.toml` and let the instance manager construct the instances
- [x] After constructing the instances, start all instances which should be started automatically `autostart=true` in the `instances.toml`
- [x] Automatically detect media repositories paths
- [x] Provide the media repositories path via Inexor Tree
- [x] Core Initialization Routine (#368)

**Comment by a-teammate** [comment]
Category: Awesome.

**Comment by a-teammate** [comment]
The only command line argument for InexorCore would be the port to InexorFlex (since otherwise Core would be blocked from starting up if the port is somehow already taken by another process).

**Comment by aschaeffer** [comment]
Correct. And I would suggest that the instance ID and the port should be the same.

**Comment by Fohlen** [comment]
Shouldn't the  `node` folder be removed from master as well? Adding that as a task.

**Comment by aschaeffer** [comment]
Already done? fa37ee2090104ab531e71627f17462771989a573

**Comment by aschaeffer** [comment]
Everything is done in flex/master, except the Core Initialization Routine (#368).

**Comment by a-teammate** [comment]
can be closed as core gets merged
