### ISSUE TITLE
Add a plan for the interface(s)

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/inexor-core#377]
As it's been discussed quiet a few times we will need a plan for the interfaces in order to replace CubeGui with CEF.

@aschaeffer and I did agree that this should be split up into different components, that are listed below:

- [ ] a HUD component that should be really BARE (since it is always rendered) (#312 + #98)
- [ ] a console component (#386)
- [ ] a lightweight menu component, that is responsible for in-game menus (the thing that appears when you press "ESC", that renders the loading screen (#342)
- [ ] the main component that includes settings, master list, repository manager (...), which does already have a repository @inexor-game/interface #402

**Comment by Croydon** [comment]
Related:
#312 
#98

**Comment by aschaeffer** [comment]
Related:
#342
https://github.com/inexor-game/code/wiki/User-interface-Menu

**Comment by Fohlen** [comment]
All of the above now are in work and have independent tickets. Closing this.
