### ISSUE TITLE
Implement a web user interface for Inexor Flex

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-core#402]
### Goals

* Manage profiles
* Manage logging (per profile)
* Manage instances (per profile)
* Manage media repositories
* Manage the server list
* Manage user interfaces
* Fetch new releases

### Tasks

- [x] Flex starts the Flex user interface
- [x] Manage (Flex) profiles
  * List profiles
  * Create, update and delete profiles (CRUD)
  * Set the default profile
  * Change the current profile (requires a restart of Inexor Flex)
- [x] Manage instances
  * List instances
  * Create, update and delete instances (CRUD)
  * Lifecycle: start, pause, resume, stop
  * Monitor: current state
  * Show / modify the `Inexor Tree` for each instance
- [x] Manage logging
  * List loggers
  * Log levels
  * Log file name
  * Log to console
- [x] Manage media repositories
  * List media repositories
- [x] Manage user interfaces
  * List user interfaces

**Comment by aschaeffer** [comment]
The package manager of favour is **yarn**.

The final result schema will be as following:

http(s)://flex_url/ui/UINAME
- dependencies will be served from flex/static/
- yarn collects dependencies from all modules
- prefix your module with @inexor-ui to indicate it's a UI on npm
- /ui is an entry alias to /ui/flex

#### Folder Structure

The folder structure of a module is proposed as following:

- package.json
- public
    - *css*
    - *js*
    - *img*
    - index.html

#### Scope

inexorgame/@inexor-ui/flex
inexorgame/@inexor-plugin/fancy-maprotation
@inexor-plugin :any

**Comment by aschaeffer** [comment]
To build the user interface for Flex:

    cd interfaces/ui-flex
    yarn install
    npm run build
    cd -

Afterwards start Flex and goto http://localhost:31416/api/v1/interfaces/ui-flex/

**Comment by Fohlen** [comment]
Thumbs up 👍
