### ISSUE TITLE
Provide the Inexor Tree to user interfaces via websockets

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-core#442]
The user interfaces (`ui-flex`, `ui-client-hud`, `ui-client-menu`, `ui-console`) need to get informed about changes on the Inexor Tree. The general problem is that a node, a sub tree or even the complete tree has to be pulled (even if there aren't any changes). Using websockets changes on the tree can be transferred without delay and is limited to the changed node only. This way we have way less overhead and faster response times.

### Goal

* Send changes on the Inexor Tree via websockets to client side (e.g. user interfaces)
  * Content of a node has changed (Inexor Tree event `postSet`)
  * A new node has been added (Inexor Tree event `add`)
* Store a copy of the Inexor Tree on client side (e.g. user interfaces)

_Note: This is the most usable way until there is real support for GRPC clients on browser side which connects directly to Inexor Core (C++)._

### Tasks

- [x] `Inexor Flex`: Integrate express websocket
  *  [express-ws](https://github.com/HenningM/express-ws)
- [x] `Inexor Flex`: Listen on tree node changes and push via websocket
  - [x] `postSet`
  - [x] `add`
- [x] `Inexor UI Client HUD`
  - [x] Integrate webpack
  - [x] Integrate `Inexor Tree` on browser side
  - [x] Receive tree node changes and update the local Inexor Tree
    - [x] `postSet`
    - [x] `add`

### Using the websockets

```javascript
  var exampleSocket = new WebSocket("ws://localhost:31416/api/v1/ws/tree", "protocolOne");
  exampleSocket.onmessage = function (event) {
    let response = event.data;
    console.log(response);
  };
```

#### Output

```javascript
...
{"state":"sync","datatype":"int64","path":"/instances/31417/rendering/screen/fullscreen","value":0}
{"state":"sync","datatype":"int64","path":"/instances/31417/rendering/screen/scr_w","value":800}
{"state":"sync","datatype":"int64","path":"/instances/31417/rendering/screen/scr_h","value":600}
...
```
### See also

* https://github.com/HenningM/express-ws
* https://developer.mozilla.org/de/docs/WebSockets

These technologies also try to bring GRPC support to the web browser.

* https://github.com/dcodeIO/ProtoBuf.js/
* https://blog.wearewizards.io/using-protobuf-instead-of-json-to-communicate-with-a-frontend
* https://github.com/grpc/grpc/grpc-web
* https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md
* https://github.com/grpc/grpc/issues/8682
* https://github.com/tmc/grpc-websocket-proxy

**Comment by aschaeffer** [comment]
Done: https://github.com/inexorgame/ui-client-hud/commit/92956a48628c96cd9771924d204b13fbcac90d03
