### ISSUE TITLE
To-Do list for 0.9.0-release

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/inexor-core#452]
## Note
If you update a ticket and include or exclude it to the release

- add or remove the milestone
- think about if it is *really* critical, and mark it with *prio:RELEASE*
- otherwise we will not make sure that it's included

## About the release
Since we're all excited about the new `0.9.0` release I wanted to note down an overall ticket on when (I, or we I assume) can define the new release as done. Please add missing tickets, but _carefully_, bloating the new release unnecessarily is not good.

- [x] Find a release name, suggestions have been
  - Speed release
  - Rolling stones release
- [x] Clean up tickets after release!
  - Divide and rule = do what must be done for release, but split big tickets to smaller ones if not everything is straightly release critical
- ~~Release at Hackathon 2017~~

> I have updated the milestone date for the 0.9.0-release to 1st of September. I think it's a very realistic day given the remaining workload, and it'd be good to have the release happen so close to the Hackathon (that will motivate the whole team, I guess). As well it will be nice to be able to announce a release at date 😸 

If we all can agree that 1st of September is definitely feasible for the next release, we can make a blog post (and social media) with an announcement for the upcoming release. Please discuss in the ticket.

## On the website
Provide a download page that tells user instructions on how to get the game, #269 @terencode ?

## On core side

- ~~add Windows icon #451~~
- [x] Fix this one, #407 
- ~~Merge #445~~ 
- [ ] add a named release `0.9.0` to the repo

## Media

- ~~Migrate `init.cfg`, #427~~

## On flex side

- [x] Implement downloads #440 
- [x] Decouple interfaces #450 
- [x] Make npm install-able #449 
  - ~~that involves designing a`man`-page, any volunteers?  #494~~
- [x] Refactor flex
  - [x] reduce eslint to `eslint:recommended` and fix all the issues with it
  - [x] all occurences of `process.cwd()` should be replaced with standard paths
    - [x] the binary path should be somewhere like user folder + 'bin'
    - [x] the proto path needs to be set to `bin/path_to_proto` as well
  - [x] all `@inexor-game/` prefixes should be renamed to `@inexorgame`
  - [x] all `TODO` passages should be resolved, if possible
  - [x] add a `.travis.yaml` that runs `npm lint, npm test` and add a build badge
- [ ] PUBLISH 🎆 via `npm publish`, in the future this might be done by Travis

PS: The `flex` refactoring tasks are perfect to get in touch with the code

**Comment by a-teammate** [comment]
good suggestions, the date looks good.
some more (imo they are necessary):

- [ ] #430 (rename proto and executable files) *[maybe optional]*
- [ ] #431 (enable RPC for servers) (necessary for server instances controlled by flex)
- [ ] merge pull request #455
    * necessary bc some flaws in the logger
    * if pr not possible at least cherry-pick the logging commit (as otherwise multiple instances will crash on windows)
    * necessary bc of #431 *(could quickfix it without merging remove_standalone probably)*


- [ ] add a bomberman map to media-essential
     * *otherwise we can not really test the bomberman mode*
- [ ] remove the texture errors and not working maps from media-essential
- [ ] doxygen@inexorgame/stable is not working for me, only doxygen@inexorgame/testing

**Comment by Croydon** [comment]
> add a bomberman map to media-essential

Only if it's 100% open source. I'm strictly vetoing adding any non-open-source files to media-essential. It is already hard enough to get the current things out of there, don't add new ones. We promised from the very beginning to be 100% open source and we still don't fullfill that promise.

Since you want it for testing, media-additional should be enough. Media-essential should be stable and open source.

> remove the texture errors and not working maps from media-essential

I will have a look at some point after tomorrow, at least when I can finally compile AND run again.

**Comment by Fohlen** [comment]
I will add the following to the list as well

- [ ] add a windows setup, see #277 
After some time thinking about @aschaeffer 's comment I think releasing the new version at the Hackathon will be a nice "marketing" thingie. So. The release date is now settled at 22. of September (or 15th).

**NOTE** please consider this ticket (and the 0.9 milestone) as locked. Don't add new tickets without prior debate. Don't add any feature tickets, only add critical bugs.

**Comment by a-teammate** [comment]
Oh and:
- [ ] on windows the APPDATA path should only get used for things the user **is not supposed to ever see**.
    * its not for media, its not for pictures, its not for demos: all of that should go into the "Documents/My Games" folder.

**Comment by Fohlen** [comment]
Can we push this further?
Do we have testers?

Maybe @movabo and @Croydon can test the automatic install routine with the graphical installer?
If everything goes well, let's finally roll out `0.9.0` release!

If we would manage to bake a `snap` for Ubuntu for the release, it would be amazing as well!

**Comment by Fohlen** [comment]
I see that we can agree on a census for the `0.9.0` release (from what I read in Riot)

The following is now to-do to actually do the release
- [ ] test the installers, windows and snap
- [ ] update the website links (there's a PR for that)
- [ ] write a CHANGELOG for inexor-core and inexor-flex
- [ ] add the 0.9.0 release tag for core and flex. Publish flex to npm.
- [ ] write and publish a blog post
