### ISSUE TITLE
Extend tree synchonization to lists and classes

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-core#454]
Currently `SharedVar`s are synchronized via the Inexor Tree. Next step is to synchronize lists/arrays and complex data structures like c++ objects. This would enables us to complete other tasks like the HUD which depends on these information.

### Tree path format

- [ ] Define a tree path format for list items
  * `/path/to/the/list/0`
  * `/path/to/the/list/1`
- [ ] Define a tree path format for objects, nested objects and 
  * `/path/to/the/object` (e.g.: `/gamestate/player1`)
  * `/path/to/the/object/attributeName` (e.g.: `/gamestate/player1/frags`)
  * `/path/to/the/object/nestedObject` (e.g.: `/gamestate/player1/position`)
  * `/path/to/the/object/nestedObject/attributeName` (e.g.: `/gamestate/player1/position/x`)
  * `/path/to/the/list` (e.g.: `/gamestate/players`)
  * `/path/to/the/list/0` (e.g.: `/gamestate/players/0`)
  * `/path/to/the/list/0/attributeName` (e.g.: `/gamestate/players/0/frags`)
  * `/path/to/the/list/0/nestedObject/attributeName` (e.g.: `/gamestate/players/0/position/x`)

### Tasks `Inexor Flex`

- [ ] Lists
  - [ ] Add a new datatype `list`
    * Which is basically a `node`
    * Don't allow to add childs using `addChild(...)`
    * Implement typical array functions for appending, inserting and sorting
  - [ ] Receive list messages
    * Append/insert new list entry
    * Update list entry value
    * Remove list entry
  - [ ] Send list messages
    * Append/insert new list entry
    * Update list entry value
    * Remove list entry
  - [ ] Extend the initialization of the Inexor Tree (recursively initialize lists)
- [ ] Objects
  - [ ] Objects in C++ are normal tree nodes (datatype `node`)
  - [ ] Receive object created messages
  - [ ] Receive object attribute messages
  - [ ] Receive object attribute messages
  - [ ] Extend the initialization of the Inexor Tree (recursively initialize objects)

### Tasks `Inexor Core`

* TODO: @a-teammate
