### ISSUE TITLE
Simplify InexorCore debugging experience

### ISSUE THREAD

**Issue by a-teammate** [inexorgame/inexor-core#462]
Currently we have a slight problem when trying to debug inexor-core (the C++-part):
We must start inexor-core through our "launcher" (inexor-flex).
Hence you need to:
* build target "INSTALL" (to copy all shit from ./build/bin to ./bin)
* start inexor-core through inexor-flex
* attach-to-process in visual studio

#### What we want is:
You press the usual "Start" button and it automatically starts Inexor-Core in a debug session.

#### setting it up
The routine for setting up the debugger in visual studio **after this issue is resolved** will be:
* Install flex globally (**once**)
* Visual Studio: Set the startup project (**once**)
     * you need to do this for cmake projects otherwise it tries to start `ALL_BUILD`
* Visual Studio: Set the debugging startup-parameter (**once**) for the to-be-debugged project
     * background: the only main arg inexor-core takes is a portnumber
     * inexor-core set ups a server to communicate with inexor-flex on that port
     * usual startup is: flex starts core, passing core a port as parameter for where flex expects a server to appear

### Todo:

**Core**
- [ ] create util/debugging.hpp and util/debugging.cpp 
   * [ ] create function is_debugger_attached()
      * [windows](https://stackoverflow.com/questions/4818628/c-figure-out-if-the-debugger-is-attached)
      * [unix](https://stackoverflow.com/a/24969863/8043980)
* [ ] if inexor-core is started in the debugger (is_debugger_attached)
    * and we built in debug-mode (#ifdef DEBUG ..)
    * start inexor-flex inside inexor-core (in the main() function before the first metapp.initialize())
    * .. go on as usual (wait on inexor-core side for flex now, .. startup .. loop..)

**Flex**
* [ ] find a way to invoke flex globally from C++ code
* [ ] find a way to tell flex to create a new instance globally from c++ code
   * (alternatively:)
      * [ ] add parameter to flex for the binary_folder
      * [ ] add a parameter to flex for the grpc port

This seems like a good first bug (the flex part needs a helping hand probably - ignore it)

**Comment by Fohlen** [comment]
finding a way to invoke flex globally from C++ code seems fairly easy

- inexor-flex will be npm-globally-installable
- hence you can start inexor-flex (or more precisely, it's command line) via `inexor-flex` from your CMD
- hence it won't be hard to start `inexor-flex?

**Comment by a-teammate** [comment]
when flex is globally installed:
how expensive would it be to listen for new inexor-core processes to be started if the developer flag is set (or: if the binary path fits one in the current instances manager)?
I think the above solution is good enough though :)

**Comment by a-teammate** [comment]
Okay the easiest way to go is simply:

If an instance has
`autostart = false`
but `autoconnect = true`
it should really do that:
If the port (the instanceid) appears to have a server running: connect to the instance.

Maybe the portscanner has a callback without timeout, or we just start the portscan again after the timeout if no instance appeared.
Maybe we could also check periodically (e.g. with https://www.npmjs.com/package/wait-until), dunno.
This would make the debugging pretty easy:
1. you start flex
2. you run the debugger as usual from inside the IDE

**Comment by aschaeffer** [comment]
I think if we solve #398 it would be able to start Inexor Core instances independently (either Visual Studio, another IDE or from a shell) and Flex would detect that an instance is already running.

**Comment by Fohlen** [comment]
Wasn't there an issue on the core side when a stream interrupts? Can multiple clients connect?

**Comment by aschaeffer** [comment]
Yes, multiple clients can connect and the RPC messages are distributed to all clients. But in this case you would start Inexor Core and then tell Inexor Flex to connect which would be the first client.
