### ISSUE TITLE
Integrate a scheduler

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-core#523]
Enhance Inexor Flex with a scheduler to trigger time-based events.

## Examples for time-based events

| Task name | Description | Schedule (examples!) |
| --- | --- | --- |
| `updateMediaRepositories` | Update media repositories | Every hour |
| `updateInterfaces` | Update interfaces | Every day |
| `updateReleaseList` | Update release list | Every day |
| `updateServerList` | Update server list | Every minute |
| `restartServerInstance` | Restart server instance | Every night |
| `autoSaveMap` | Automatically saves the current map in a coop edit session | Every minute |

You got the idea.

## Tasks

- [ ] Inexor Tree
  * `/scheduler/{taskName}`
    * `/description`
    * `/cronPattern`
    * `/action`
      * `/service`
      * `/method`
      * `/parameters/{parameterName}` = parameterValue
- [ ] SchedulerManager
  - [ ] `updateScheduler()`
    * Initializes or reinitializes the scheduler using the scheduler tasks
  - [ ] `executeAction(taskNode)`
    * Resolves the given `service` from the applicationContext and executes the `method` using the given parameters 
  - [ ] `loadConfig(filename = 'scheduler.toml')`
  - [ ] `saveConfig(filename = 'scheduler.toml')`
- [ ] UI Flex
  - [ ] List tasks
  - [ ] Create new task
  - [ ] Edit task

## See also

* https://www.npmjs.com/package/node-schedule

**Comment by a-teammate** [comment]
Doesn't this actually belong into a user plugin?
I mean besides the autosave usecase none is really critical for our future development.
And why not just autosave after changes are made?

**Comment by aschaeffer** [comment]
examples! :-)

**Comment by aschaeffer** [comment]
This feature isn't meant for developers but server administrators and end users. Server admins and end users simply doesn't have to do these tasks manually any more. It also helps to reduce the support questions, because content and user interfaces are kept up to date without any action required by the server admin or end user. Also plugin developers can use the scheduler for their needs.
