### ISSUE TITLE
Creating Edit Menu UIs

### ISSUE THREAD

**Issue by MartinMuzatko** [inexorgame/inexor-core#587]
This issue contains the next discussion for planning the next steps of the editing menu

The main document to work with is here: https://github.com/inexorgame/inexor-core/wiki/Edit-Menu-UIs

To contribute, please discuss your concerns or questions here in this issue. Otherwise you can add your ideas to the wiki directly.

**Current tasks:**

* [ ] Define what pages/menus we need
  * [ ] Define contents, actions for each page
* [ ] Define how to get to these menus (Keybindings? Menu point in main menu while editing?)

**Roadmap:**

* [ ] Define roughly which contents we need to display and in which menus this can fit into
* [ ] Finish the first iteration of the [main menu](#586), to re-use components for the edit menus.

**Comment by a-teammate** [comment]
Related maybe: #473 (pinning UIs on cube surfaces)

**Comment by MartinMuzatko** [comment]
Also related: #115 #363
